export const verifiedSeedDonors = [
  {
    id: "CL-2026-VD-001",
    firstName: "Arjun",
    lastName: "Khadka",
    age: 29,
    gender: "Male",
    phone: "+977-9811110001",
    email: "arjun.khadka@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Maharajgunj",
    street: "Ward 21, Maharajgunj Road",
    bloodType: "O+",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Maharajgunj, Kathmandu",
    registrationDate: "2026-03-10T09:00:00.000Z",
    medicalReport: {
      height: "175",
      weight: "70",
      bloodPressure: "118/76",
      heartRate: "72",
      medicalHistory: "No significant past history",
      labResults: "CBC within normal limits",
      hlaA: "A*01:01",
      hlaB: "B*07:02",
      hlaC: "C*01:02",
      hlaDRB1: "DRB1*01:01",
      hlaDQB1: "DQB1*02:01",
      hlaType: "A*01:01, B*07:02, C*01:02, DRB1*01:01, DQB1*02:01",
      doctorNotes: "Fit for donation",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-arjun.pdf",
      reportFileData: null,
      submittedAt: "2026-03-12T14:30:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-002",
    firstName: "Sita",
    lastName: "Maharjan",
    age: 34,
    gender: "Female",
    phone: "+977-9811110002",
    email: "sita.maharjan@example.com",
    province: "Bagmati",
    district: "Lalitpur",
    municipality: "Patan",
    street: "Ward 10, Lalitpur Sub-city",
    bloodType: "A+",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Patan, Lalitpur",
    registrationDate: "2026-03-08T11:20:00.000Z",
    medicalReport: {
      height: "162",
      weight: "60",
      bloodPressure: "116/74",
      heartRate: "70",
      medicalHistory: "Intermittent seasonal allergies",
      labResults: "CBC and LFT normal",
      hlaA: "A*02:01",
      hlaB: "B*08:01",
      hlaC: "C*07:02",
      hlaDRB1: "DRB1*03:01",
      hlaDQB1: "DQB1*02:01",
      hlaType: "A*02:01, B*08:01, C*07:02, DRB1*03:01, DQB1*02:01",
      doctorNotes: "Eligible, no contraindications",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-sita.pdf",
      reportFileData: null,
      submittedAt: "2026-03-11T16:00:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-003",
    firstName: "Prakash",
    lastName: "Rai",
    age: 27,
    gender: "Male",
    phone: "+977-9811110003",
    email: "prakash.rai@example.com",
    province: "Bagmati",
    district: "Bhaktapur",
    municipality: "Bhaktapur",
    street: "Ward 14, Durbar Square Road",
    bloodType: "B+",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Bhaktapur",
    registrationDate: "2026-03-05T08:45:00.000Z",
    medicalReport: {
      height: "168",
      weight: "65",
      bloodPressure: "120/78",
      heartRate: "74",
      medicalHistory: "Active lifestyle, non-smoker",
      labResults: "CBC, LFT, KFT all normal",
      hlaA: "A*03:01",
      hlaB: "B*35:01",
      hlaC: "C*04:01",
      hlaDRB1: "DRB1*04:05",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*03:01, B*35:01, C*04:01, DRB1*04:05, DQB1*03:01",
      doctorNotes: "Strong candidate for donation",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-prakash.pdf",
      reportFileData: null,
      submittedAt: "2026-03-07T10:00:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-004",
    firstName: "Maya",
    lastName: "Gurung",
    age: 31,
    gender: "Female",
    phone: "+977-9811110004",
    email: "maya.gurung@example.com",
    province: "Bagmati",
    district: "Makwanpur",
    municipality: "Hetauda",
    street: "Ward 6, Hetauda Sub-metropolis",
    bloodType: "AB+",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Hetauda, Makwanpur",
    registrationDate: "2026-03-06T12:30:00.000Z",
    medicalReport: {
      height: "165",
      weight: "58",
      bloodPressure: "114/72",
      heartRate: "68",
      medicalHistory: "No chronic illness",
      labResults: "Normal range for all tests",
      hlaA: "A*11:01",
      hlaB: "B*44:02",
      hlaC: "C*16:01",
      hlaDRB1: "DRB1*07:01",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*11:01, B*44:02, C*16:01, DRB1*07:01, DQB1*03:01",
      doctorNotes: "Eligible for unrelated HSCT",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-maya.pdf",
      reportFileData: null,
      submittedAt: "2026-03-10T09:15:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-005",
    firstName: "Suresh",
    lastName: "Rai",
    age: 35,
    gender: "Male",
    phone: "+977-9811110005",
    email: "suresh.rai2@example.com",
    province: "Bagmati",
    district: "Kavrepalanchok",
    municipality: "Banepa",
    street: "Ward 8, Banepa Bazaar",
    bloodType: "O-",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Banepa, Kavrepalanchok",
    registrationDate: "2026-03-09T14:00:00.000Z",
    medicalReport: {
      height: "172",
      weight: "68",
      bloodPressure: "117/75",
      heartRate: "71",
      medicalHistory: "Occasional back pain, otherwise healthy",
      labResults: "All parameters within normal limits",
      hlaA: "A*24:02",
      hlaB: "B*51:01",
      hlaC: "C*07:02",
      hlaDRB1: "DRB1*11:01",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*24:02, B*51:01, C*07:02, DRB1*11:01, DQB1*03:01",
      doctorNotes: "Donor meets eligibility criteria",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-suresh.pdf",
      reportFileData: null,
      submittedAt: "2026-03-12T11:45:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-006",
    firstName: "Nisha",
    lastName: "Shrestha",
    age: 26,
    gender: "Female",
    phone: "+977-9811110006",
    email: "nisha.shrestha@example.com",
    province: "Bagmati",
    district: "Lalitpur",
    municipality: "Lalitpur Sub-metropolis",
    street: "Ward 13, Mahalaxmi Road",
    bloodType: "A-",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Lalitpur",
    registrationDate: "2026-03-04T10:00:00.000Z",
    medicalReport: {
      height: "160",
      weight: "55",
      bloodPressure: "115/70",
      heartRate: "69",
      medicalHistory: "No known allergies",
      labResults: "Healthy lab profile",
      hlaA: "A*01:01",
      hlaB: "B*35:01",
      hlaC: "C*07:02",
      hlaDRB1: "DRB1*03:01",
      hlaDQB1: "DQB1*02:01",
      hlaType: "A*01:01, B*35:01, C*07:02, DRB1*03:01, DQB1*02:01",
      doctorNotes: "Eligible verified donor",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-nisha.pdf",
      reportFileData: null,
      submittedAt: "2026-03-06T13:20:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-007",
    firstName: "Binod",
    lastName: "K.C.",
    age: 28,
    gender: "Male",
    phone: "+977-9811110007",
    email: "binod.kc@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Maharajgunj",
    street: "Ward 16, New Road",
    bloodType: "B-",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Maharajgunj, Kathmandu",
    registrationDate: "2026-03-03T09:30:00.000Z",
    medicalReport: {
      height: "174",
      weight: "72",
      bloodPressure: "119/77",
      heartRate: "73",
      medicalHistory: "Physically active",
      labResults: "Normal blood panel",
      hlaA: "A*02:01",
      hlaB: "B*07:02",
      hlaC: "C*01:02",
      hlaDRB1: "DRB1*01:01",
      hlaDQB1: "DQB1*02:01",
      hlaType: "A*02:01, B*07:02, C*01:02, DRB1*01:01, DQB1*02:01",
      doctorNotes: "Approved for donation",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-binod.pdf",
      reportFileData: null,
      submittedAt: "2026-03-05T15:10:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-008",
    firstName: "Rina",
    lastName: "Basnet",
    age: 33,
    gender: "Female",
    phone: "+977-9811110008",
    email: "rina.basnet@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Kirtipur",
    street: "Ward 2, Kirtipur Road",
    bloodType: "AB-",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Kirtipur, Kathmandu",
    registrationDate: "2026-03-02T13:00:00.000Z",
    medicalReport: {
      height: "163",
      weight: "59",
      bloodPressure: "117/76",
      heartRate: "71",
      medicalHistory: "No chronic conditions",
      labResults: "Healthy hematology results",
      hlaA: "A*03:01",
      hlaB: "B*08:01",
      hlaC: "C*07:02",
      hlaDRB1: "DRB1*04:05",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*03:01, B*08:01, C*07:02, DRB1*04:05, DQB1*03:01",
      doctorNotes: "Donor is medically cleared",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-rina.pdf",
      reportFileData: null,
      submittedAt: "2026-03-04T11:50:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-009",
    firstName: "Deepak",
    lastName: "Thapa",
    age: 30,
    gender: "Male",
    phone: "+977-9811110009",
    email: "deepak.thapa@example.com",
    province: "Bagmati",
    district: "Bhaktapur",
    municipality: "Bhaktapur",
    street: "Ward 5, Suryavinayak Road",
    bloodType: "A+",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Bhaktapur",
    registrationDate: "2026-03-01T10:15:00.000Z",
    medicalReport: {
      height: "170",
      weight: "67",
      bloodPressure: "118/74",
      heartRate: "72",
      medicalHistory: "Healthy, regular exercise",
      labResults: "All labs normal",
      hlaA: "A*11:01",
      hlaB: "B*07:02",
      hlaC: "C*01:02",
      hlaDRB1: "DRB1*01:01",
      hlaDQB1: "DQB1*06:02",
      hlaType: "A*11:01, B*07:02, C*01:02, DRB1*01:01, DQB1*06:02",
      doctorNotes: "Candidate approved for registry",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-deepak.pdf",
      reportFileData: null,
      submittedAt: "2026-03-03T14:40:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-010",
    firstName: "Pooja",
    lastName: "Sharma",
    age: 29,
    gender: "Female",
    phone: "+977-9811110010",
    email: "pooja.sharma@example.com",
    province: "Bagmati",
    district: "Lalitpur",
    municipality: "Patan",
    street: "Ward 18, Jhamsikhel Road",
    bloodType: "O+",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Patan, Lalitpur",
    registrationDate: "2026-03-01T09:00:00.000Z",
    medicalReport: {
      height: "166",
      weight: "62",
      bloodPressure: "115/73",
      heartRate: "70",
      medicalHistory: "Healthy, no allergies",
      labResults: "Normal blood panel",
      hlaA: "A*24:02",
      hlaB: "B*44:02",
      hlaC: "C*16:01",
      hlaDRB1: "DRB1*07:01",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*24:02, B*44:02, C*16:01, DRB1*07:01, DQB1*03:01",
      doctorNotes: "Verified eligible donor",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-pooja.pdf",
      reportFileData: null,
      submittedAt: "2026-03-02T12:20:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-011",
    firstName: "Sabina",
    lastName: "Bhandari",
    age: 28,
    gender: "Female",
    phone: "+977-9811110011",
    email: "sabina.bhandari@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Thamel",
    street: "Ward 05, Thamel Marg",
    bloodType: "A+",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Thamel, Kathmandu",
    registrationDate: "2026-03-11T10:30:00.000Z",
    medicalReport: {
      height: "161",
      weight: "56",
      bloodPressure: "116/72",
      heartRate: "68",
      medicalHistory: "Non-smoker, healthy diet",
      labResults: "Blood counts normal",
      hlaA: "A*01:01",
      hlaB: "B*08:01",
      hlaC: "C*07:02",
      hlaDRB1: "DRB1*03:01",
      hlaDQB1: "DQB1*02:01",
      hlaType: "A*01:01, B*08:01, C*07:02, DRB1*03:01, DQB1*02:01",
      doctorNotes: "Eligible and cleared for donation",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-sabina.pdf",
      reportFileData: null,
      submittedAt: "2026-03-13T09:20:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-012",
    firstName: "Manoj",
    lastName: "Shrestha",
    age: 32,
    gender: "Male",
    phone: "+977-9811110012",
    email: "manoj.shrestha@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "New Baneshwor",
    street: "Ward 16, New Baneshwor",
    bloodType: "O+",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "New Baneshwor, Kathmandu",
    registrationDate: "2026-03-12T09:15:00.000Z",
    medicalReport: {
      height: "174",
      weight: "68",
      bloodPressure: "118/76",
      heartRate: "72",
      medicalHistory: "Regular exercise",
      labResults: "Normal metabolic profile",
      hlaA: "A*02:01",
      hlaB: "B*07:02",
      hlaC: "C*01:02",
      hlaDRB1: "DRB1*01:01",
      hlaDQB1: "DQB1*05:01",
      hlaType: "A*02:01, B*07:02, C*01:02, DRB1*01:01, DQB1*05:01",
      doctorNotes: "Eligible for unrelated donation",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-manoj.pdf",
      reportFileData: null,
      submittedAt: "2026-03-14T15:30:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-013",
    firstName: "Ritu",
    lastName: "Joshi",
    age: 26,
    gender: "Female",
    phone: "+977-9811110013",
    email: "ritu.joshi@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Kalanki",
    street: "Ward 18, Kalanki Road",
    bloodType: "B+",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Kalanki, Kathmandu",
    registrationDate: "2026-03-08T14:10:00.000Z",
    medicalReport: {
      height: "164",
      weight: "59",
      bloodPressure: "117/74",
      heartRate: "70",
      medicalHistory: "Healthy with mild seasonal allergies",
      labResults: "All labs within normal range",
      hlaA: "A*11:01",
      hlaB: "B*35:01",
      hlaC: "C*04:01",
      hlaDRB1: "DRB1*04:05",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*11:01, B*35:01, C*04:01, DRB1*04:05, DQB1*03:01",
      doctorNotes: "Candidate approved for registry",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-ritu.pdf",
      reportFileData: null,
      submittedAt: "2026-03-10T11:00:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-014",
    firstName: "Nabin",
    lastName: "Gautam",
    age: 29,
    gender: "Male",
    phone: "+977-9811110014",
    email: "nabin.gautam@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Tripureshwor",
    street: "Ward 24, Tripureshwor Chowk",
    bloodType: "AB+",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Tripureshwor, Kathmandu",
    registrationDate: "2026-03-07T08:50:00.000Z",
    medicalReport: {
      height: "177",
      weight: "70",
      bloodPressure: "120/78",
      heartRate: "73",
      medicalHistory: "No chronic illness",
      labResults: "Healthy blood report",
      hlaA: "A*03:01",
      hlaB: "B*44:02",
      hlaC: "C*16:01",
      hlaDRB1: "DRB1*07:01",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*03:01, B*44:02, C*16:01, DRB1*07:01, DQB1*03:01",
      doctorNotes: "Verified applicable donor",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-nabin.pdf",
      reportFileData: null,
      submittedAt: "2026-03-09T15:10:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-015",
    firstName: "Kanchan",
    lastName: "KC",
    age: 34,
    gender: "Female",
    phone: "+977-9811110015",
    email: "kanchan.kc@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Budhanilkantha",
    street: "Ward 02, Budhanilkantha Road",
    bloodType: "O-",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Budhanilkantha, Kathmandu",
    registrationDate: "2026-03-05T16:20:00.000Z",
    medicalReport: {
      height: "168",
      weight: "63",
      bloodPressure: "117/75",
      heartRate: "71",
      medicalHistory: "No allergies",
      labResults: "Normal CBC and metabolic profile",
      hlaA: "A*24:02",
      hlaB: "B*51:01",
      hlaC: "C*07:02",
      hlaDRB1: "DRB1*11:01",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*24:02, B*51:01, C*07:02, DRB1*11:01, DQB1*03:01",
      doctorNotes: "Eligible and medically cleared",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-kanchan.pdf",
      reportFileData: null,
      submittedAt: "2026-03-07T13:45:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-016",
    firstName: "Suman",
    lastName: "Thapa",
    age: 30,
    gender: "Male",
    phone: "+977-9811110016",
    email: "suman.thapa@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Kapan",
    street: "Ward 14, Kapan Road",
    bloodType: "A-",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Kapan, Kathmandu",
    registrationDate: "2026-03-09T12:30:00.000Z",
    medicalReport: {
      height: "173",
      weight: "69",
      bloodPressure: "116/74",
      heartRate: "70",
      medicalHistory: "Occasional headache, otherwise healthy",
      labResults: "Normal to healthy lab values",
      hlaA: "A*01:01",
      hlaB: "B*35:01",
      hlaC: "C*07:02",
      hlaDRB1: "DRB1*03:01",
      hlaDQB1: "DQB1*02:01",
      hlaType: "A*01:01, B*35:01, C*07:02, DRB1*03:01, DQB1*02:01",
      doctorNotes: "Approved for donation",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-suman.pdf",
      reportFileData: null,
      submittedAt: "2026-03-11T08:40:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-017",
    firstName: "Anjali",
    lastName: "Rana",
    age: 27,
    gender: "Female",
    phone: "+977-9811110017",
    email: "anjali.rana@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Baluwatar",
    street: "Ward 05, Baluwatar Road",
    bloodType: "B+",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Baluwatar, Kathmandu",
    registrationDate: "2026-03-10T11:00:00.000Z",
    medicalReport: {
      height: "165",
      weight: "57",
      bloodPressure: "115/72",
      heartRate: "69",
      medicalHistory: "No chronic conditions",
      labResults: "Normal hematology and biochemistry",
      hlaA: "A*02:01",
      hlaB: "B*08:01",
      hlaC: "C*07:02",
      hlaDRB1: "DRB1*03:01",
      hlaDQB1: "DQB1*02:01",
      hlaType: "A*02:01, B*08:01, C*07:02, DRB1*03:01, DQB1*02:01",
      doctorNotes: "Eligible donor, no contraindications",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-anjali.pdf",
      reportFileData: null,
      submittedAt: "2026-03-12T13:00:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-018",
    firstName: "Paras",
    lastName: "Chettri",
    age: 31,
    gender: "Male",
    phone: "+977-9811110018",
    email: "paras.chettri@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Sundhara",
    street: "Ward 03, Sundhara Road",
    bloodType: "B-",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Sundhara, Kathmandu",
    registrationDate: "2026-03-10T14:10:00.000Z",
    medicalReport: {
      height: "176",
      weight: "71",
      bloodPressure: "119/76",
      heartRate: "72",
      medicalHistory: "Healthy",
      labResults: "All values normal",
      hlaA: "A*02:01",
      hlaB: "B*07:02",
      hlaC: "C*01:02",
      hlaDRB1: "DRB1*01:01",
      hlaDQB1: "DQB1*05:01",
      hlaType: "A*02:01, B*07:02, C*01:02, DRB1*01:01, DQB1*05:01",
      doctorNotes: "Approved for stem cell donation",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-paras.pdf",
      reportFileData: null,
      submittedAt: "2026-03-12T16:30:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-019",
    firstName: "Meera",
    lastName: "Dahal",
    age: 28,
    gender: "Female",
    phone: "+977-9811110019",
    email: "meera.dahal@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "New Baneshwor",
    street: "Ward 14, New Baneshwor",
    bloodType: "AB-",
    sampleMethod: "Hospital Visit",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "New Baneshwor, Kathmandu",
    registrationDate: "2026-03-09T08:20:00.000Z",
    medicalReport: {
      height: "162",
      weight: "57",
      bloodPressure: "114/72",
      heartRate: "69",
      medicalHistory: "No major history",
      labResults: "Normal blood panel",
      hlaA: "A*03:01",
      hlaB: "B*44:02",
      hlaC: "C*16:01",
      hlaDRB1: "DRB1*07:01",
      hlaDQB1: "DQB1*03:01",
      hlaType: "A*03:01, B*44:02, C*16:01, DRB1*07:01, DQB1*03:01",
      doctorNotes: "Donor cleared for registry",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-meera.pdf",
      reportFileData: null,
      submittedAt: "2026-03-11T10:40:00.000Z",
    },
  },
  {
    id: "CL-2026-VD-020",
    firstName: "Sajan",
    lastName: "KC",
    age: 33,
    gender: "Male",
    phone: "+977-9811110020",
    email: "sajan.kc2@example.com",
    province: "Bagmati",
    district: "Kathmandu",
    municipality: "Jawalakhel",
    street: "Ward 11, Jawalakhel Road",
    bloodType: "O+",
    sampleMethod: "Courier Pickup",
    sampleStatus: "completed",
    status: "report_submitted",
    location: "Jawalakhel, Kathmandu",
    registrationDate: "2026-03-08T08:40:00.000Z",
    medicalReport: {
      height: "175",
      weight: "69",
      bloodPressure: "117/74",
      heartRate: "71",
      medicalHistory: "Healthy and active",
      labResults: "All laboratory results within normal limits",
      hlaA: "A*01:01",
      hlaB: "B*07:02",
      hlaC: "C*01:02",
      hlaDRB1: "DRB1*01:01",
      hlaDQB1: "DQB1*02:01",
      hlaType: "A*01:01, B*07:02, C*01:02, DRB1*01:01, DQB1*02:01",
      doctorNotes: "Donor is eligible for unrelated matches",
      eligibility: "eligible",
      rejectionReason: null,
      reportFileName: "report-sajan.pdf",
      reportFileData: null,
      submittedAt: "2026-03-10T14:55:00.000Z",
    },
  },
];

export function seedVerifiedDonors() {
  try {
    const existing = JSON.parse(localStorage.getItem('allDonors') || '[]');
    const approvedSeeds = verifiedSeedDonors.map((donor) => ({
      ...donor,
      status: "approved",
      approvedDate: donor.registrationDate || new Date().toISOString(),
    }));

    const approvedMap = new Map(approvedSeeds.map((donor) => [donor.id, donor]));
    const mergedExisting = existing.map((donor: any) => {
      if (approvedMap.has(donor.id)) {
        return {
          ...donor,
          ...approvedMap.get(donor.id),
        };
      }
      return donor;
    });

    const existingIds = new Set(existing.map((donor: any) => donor.id));
    const donorsToAdd = approvedSeeds.filter((donor) => !existingIds.has(donor.id));

    const merged = [...mergedExisting, ...donorsToAdd];
    localStorage.setItem('allDonors', JSON.stringify(merged));
    return merged;
  } catch (error) {
    console.error('Failed to seed verified donors:', error);
    return JSON.parse(localStorage.getItem('allDonors') || '[]');
  }
}

